language: node_js
node_js:
- '0.10'
env:
  global:
    secure: DGGl73QxMko+K6qYYixtG5bCXkCbm8hI130Y3tTj8W6jGaE3Mq+lIyK3W8sIZkjShR/W4/WT2YNHnINy14jFP2bqZd2aW0OmJNsrbCOqhwAGV+fjNOxDB+BADXfoIUqVS5GlWe+T5215F9zrLuwHf6cgBz0UHGLIzX6LW03LeYs=
after_success:
- npm install -g bower grunt-cli && bower install && git config --global user.name "Travis-CI" && git config --global user.email "travisci@theworkdept.com" && grunt deploytravis > /dev/null 2>&1
